stages:
  - build
  - deploy

variables:
  BUCKET_NAME: "movelt-front"
  GCLOUD_PROJECT: "moveltdb"
  GCLOUD_SERVICE_KEY: "ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAibW92ZWx0ZGIiLAogICJwcml2YXRlX2tleV9pZCI6ICI4ZjgzMzExNTExNTM4OWJjZjkzNWQwNDhjNmEyZWIzZmMxMWQ1NjJkIiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdndJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLa3dnZ1NsQWdFQUFvSUJBUURRaGVUaWRTT28vNUE3XG5wMGdOVkNHYkIyYmdCWUxnTWFQQ29vQWNEM2huc3ZEUTFEUzJkQ2NxSjdqZmN5Q2hCNDFPU0ExNTNqdGNRZmVMXG5HeXF3aFYyZU5NcTdBVTBUSnJwdXlrbitUWEZtMm5Sd25uYVh3dVBESlVIbzNnV3VVdytUU3BBU0VUdnYyWXUvXG5wV1JlNm9NTEd0UkJkckhsdjBLL25SVXdUYnRGOVVlOGZULzRqM0kvcmpjejdsT0F6cUwybWJQUlFmUnBaa2gwXG5wL0o5Z3k0V3kxL1Z4K1dRenJEZFM4amVWUmxGcEtCY1Y0TnE3NjE0ejltbU1OR3ZlY21NMENMelJ6RmNPWWxhXG5nd1JRT1NMTVpQNCt2VTh0Z3M2Mkp4Y1Nrb2l6NkJBZXMvODNkbFNhRUMwTkx2QlBwU1Y1RXUwZlpUeGl3V1NEXG50QnVsK0dGTkFnTUJBQUVDZ2dFQUpMeVNHSHQrcnRWbmVicjg3S3czeDNKRVk0OVZBVjU5ZFZyZnF4SG1xbzVSXG44dGlQK056NTBXbHlIcHZQMGM3Y3pEL1JiL2tCQ0QzdStLanVtbTdFa1l6SGNxN0YvMnZCU0tlRzViQ0xIQTI4XG5tZUt4RGdlZHpOR1JqUThnZlJmUkZLZjhQZEtmZHFBakNMNkFzbUFxZWhoZDhMS1NvT0ZUUnlMTGl0a0c5MG52XG5yTVRQM0ZMMXNyaDBNOTMxVjVISFRpN3dLamFwc1phTU5qN2RIWkc1S3ZHMHE1VDBQbUpVblBhSGJUa3J0YTVEXG5MTnJqMmkvdUF0bWk1NGltZTIzN3IrbnBYaTMzaVNBaGtIQTRWU2hUN2lLUmIzWEdzVFo1bGpXRnprbkpNTUFhXG5ldDQvT1BSaVB3Q0MweXRRWUN6Z2VwRjBmT0hTVkhSNjNiYkdpNkEwd1FLQmdRRDFYblp2OWdVSmZSdWZtRlNVXG5za1lEMlZQV1o4ZFd3Q0cwWE9Wbm93RFFIZkY2Qzg1QzhsOG9tSnVaTFE4YVRkSUc5L05jbnlPSDR6NktLZy9BXG4rbm5nK0tBN3JHdEFiVVZnM09OS2ZFeERlNFM5bzZmT2hURW83MlBxQUY4K09XYTFRNW1FVmxjQU1VdTJjSDN4XG5IYVlpLzdSUlVQWDAvYlZrV0pMMC9Vd2NWUUtCZ1FEWmpzQVJ2MWM4UHRKNDAySFlPZi9qY3ltY0hKRkhJOGszXG5oMDUyaU1PVXo2NGpaaW9RS2dUY3E5b3IrUmtaU2l1MlhsdmpSN05QUUNzT3pnc0dtRUVSNlB1Qkd2a1U2clErXG5IajUyTEJFMTZRS3NVVS85U1o0ckQzWnFaMDVsbXZza1B4VjNrajRUL1pJQTF5MjBDdjFhdTAra0lybjQ1aWppXG5ScXpmMVFBcEdRS0JnUUM2eHBoRGE3T3o0RjhKb213bjhIaHBiNkpvNEFDV1laU0dkZnhPWW44NDdNSW5GQnVEXG5USG54TGhHcmpPZ2xMcjNFZmpQcStseVNrUUhITEhObmc0TUpKRmpjYzhnRWQrbEs3WG02OWxrYk9VZjNEeitxXG5iaXJZclRtU0k0eGNrbGREZmR5N0p2bjg5SWxjcTg3Q25yNGJnQ2ZqaWt4Zm5FemF3SzNFL1pkVkxRS0JnUUN4XG5JbmxmK2RxZFFzazdkMkNESFRZcml1aW1JdHhtZjh5bFdaV1pEV0d4R0NkQXl6NFVTeUlLU2lJcEMzaFVEdi9vXG5USXVrVWd5OHloSkV5NTVPa0VqcXZEZUt0dHQzSEdJRThic0puSGVtM1VFLzdEU2tsZndpTTBURy9iWG5KSGkyXG4ybVl3SlBKR2RIOGNFQmMyTUh4NEUycVV5WEdDSm1QRFdLZ0kxdlI2Z1FLQmdRRFd0eWNYNER5UmIyeWd5U1VyXG4rUFZCcTNtQVhXSWtpckhpNHJ2d2crS0loWTZLQWpETW83bmY0Slhqb0dsSlEwOE1ETWxvN1pUT0g4L2pWM1ZNXG5pRHFOMnF1dTRYS0QyRDYvdnFCYXRLMkYwNis1aTFrMDJFV2x0TUhhUmx4TGticjRLR09IQmU3KzcxZ1ZnNCtiXG5wY0p6ckdCWGZzZkdsZ1p5c3JuMmtYa0dvUT09XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAiY2RnaXRsYWJAbW92ZWx0ZGIuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTA4MTE4Mjg2Mjk1NDg3NDYwODMxIiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9jZGdpdGxhYiU0MG1vdmVsdGRiLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAidW5pdmVyc2VfZG9tYWluIjogImdvb2dsZWFwaXMuY29tIgp9Cg=="

cache:
  paths:
    - node_modules/

build-job:
  stage: build
  image: node:18
  script:
    - echo "Installing dependencies..."
    - npm install
    - echo "Building the frontend..."
    - npm run build
  artifacts:
    paths:
      - build/

# Deploy job to upload files to Google Cloud Storage
deploy-job:
  stage: deploy
  image: google/cloud-sdk:latest
  before_script:
    - if [ -z "$GCLOUD_SERVICE_KEY" ]; then echo "GCLOUD_SERVICE_KEY is empty"; exit 1; fi
    - echo $GCLOUD_SERVICE_KEY | base64 -d > ${CI_PROJECT_DIR}/moveltdb-8f8331151153.json || (echo "Failed to decode GCLOUD_SERVICE_KEY"; exit 1)
    - gcloud auth activate-service-account --key-file=${CI_PROJECT_DIR}/moveltdb-8f8331151153.json
    - gcloud config set project $GCLOUD_PROJECT
  script:
    - echo "Deploying to Google Cloud Storage..."
    - gsutil -m cp -r dist/* gs://movelt-front/
  only:
    - main
