



POST http://localhost:8080/api/favorites HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTczMTQzMjUxNSwiZXhwIjoxNzMxNTE4OTE1fQ.0A2Vnc_CVgkkJCBNJ7aVmHn-9WLwmJubXC2yoonb650

{
  "userId": 1,
  "productId": 123
}